version: '3'

services:
  
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15671:15672"
  sender:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
  receiver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
      - sender

  mongo:
    hostname: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
